version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:8080"
    restart: always
    networks:
      - sql_network
    depends_on:
      - db
  db:
    env_file:
      - .env
    image: mysql:8.0
    user: root
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    ports:
      - "3306:3306"
    restart: always
    networks:
      - sql_network


networks:
  sql_network:
    driver: bridge
