apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: burguer-app-config
                  key: MYSQL_ROOT_PASSWORD
                  optional: false
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: burguer-app-config
                  key: MYSQL_DATABASE
                  optional: false
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: burguer-app-config
                  key: MYSQL_USER
                  optional: false
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: burguer-app-config
                  key: MYSQL_PASSWORD
                  optional: false
          image: mysql:8.0
          name: mysql
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "2"
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mysql-initdb
          configMap:
            name: burguer-app-config
