apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: burguer-app
  name: burguer-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: burguer-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: burguer-app
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: burguer-app-config
                  key: MYSQL_DATABASE
                  optional: false
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: burguer-app-config
                  key: MYSQL_USER
                  optional: false
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: burguer-app-config
                  key: MYSQL_PASSWORD
                  optional: false
          image: caramassada/51-burguer-app:1.0
          imagePullPolicy: IfNotPresent
          name: 51-burguer-app
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 500m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
