version: '3.8'

services:
  db:
    env_file:
      - .env
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: sqlserver
    environment:
      - MSSQL_SA_PASSWORD={$MSSQL_SA_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_ENABLE_HADR=1
      - MSSQL_TCP_PORT=1433
      - MSSQL_AGENT_ENABLED=true

    ports:
      - "1433:1433"
    restart: unless-stopped
    networks:
      - sql_network
    volumes:
      - ./database:/var/opt/mssql/data
networks:
  sql_network:
    driver: bridge