version: '3.8'

services:
  db:
    env_file:
      - .env
    image: mysql:8.0
    user: root
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - sql_network
    volumes:
      - ./database1:/var/lib/mysql
  web:
    image: 51-burguer-app
    ports:
      - "8787:8080"
    networks:
      - sql_network
    depends_on:
      - db


networks:
  sql_network:
    driver: bridge
